# fly.toml app configuration file generated for clairkeys-omr
app = "clairkeys-omr"
primary_region = "nrt" # Tokyo for Asian users
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile.audiveris"

[deploy]
  release_command = "echo 'OMR Service deploying...'"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"
  ENVIRONMENT = "production"
  LOG_LEVEL = "INFO"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[http_service.concurrency]
  type = "requests"
  hard_limit = 25
  soft_limit = 20

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[[mounts]]
  source = "omr_data"
  destination = "/data"
  initial_size = "3gb"

[metrics]
  port = 9091
  path = "/metrics"