"""Conservative, version-specific internal meter retry (D-049).

These guards do not certify musical correctness. They never edit exported XML.
"""
from collections import Counter
from fractions import Fraction
from pathlib import Path
import xml.etree.ElementTree as ET
import zipfile

from omr.musicxml_timing import scan_score
from omr.converter import MusicXMLToClairKeysConverter


def _uniform_meter(root, numerator):
    parts = root.findall('part')
    if len(parts) != 1:
        return False
    measures = parts[0].findall('measure')
    if not measures or measures[0].find('attributes/time') is None:
        return False
    times = root.findall('.//attributes/time')
    return bool(times) and all(
        len(time.findall('beats')) == len(time.findall('beat-type')) == 1
        and time.findtext('beats') == numerator and time.findtext('beat-type') == '8'
        and time.find('senza-misura') is None for time in times)


def _overflows(root):
    return sum(warning['code'] == 'measure-overflow'
               for warning in scan_score(root, lambda _: None).warnings)


def retry_is_eligible(root):
    if not _uniform_meter(root, '6'):
        return False
    count = _overflows(root)
    return count >= 2 and count * 2 >= len(root.findall('part/measure'))


def _pitches(root):
    return Counter((note.findtext('pitch/step'), note.findtext('pitch/alter', '0'),
                    note.findtext('pitch/octave'), note.findtext('staff', '1'))
                   for note in root.findall('part/measure/note') if note.find('pitch') is not None)


def _tempo_marks(root):
    sounds = Counter(Fraction(sound.get('tempo')) for sound in root.iter('sound') if sound.get('tempo'))
    metronomes = Counter(tuple((child.tag, (child.text or '').strip()) for child in mark)
                         for mark in root.iter('metronome'))
    opening = scan_score(root, MusicXMLToClairKeysConverter()._find_tempo).opening_tempo
    return sounds, metronomes, opening


def accept_meter_retry(original, candidate):
    if not _uniform_meter(candidate, '9'):
        return False
    structure = lambda root: [(part.get('id'), [m.get('number') for m in part.findall('measure')])
                              for part in root.findall('part')]
    return (structure(original) == structure(candidate)
            and not (_pitches(original) - _pitches(candidate))
            and _tempo_marks(original) == _tempo_marks(candidate)
            and _overflows(candidate) < _overflows(original))


def prepare_meter_retry(source: Path, target: Path, classify):
    """Write a separate copied graph only when both selected numerators agree.

    Returns per-staff evidence or None (abstain). IO/parse/classifier errors are
    left for the caller to log and fall back. The source archive stays intact.
    """
    with zipfile.ZipFile(source) as archive:
        # Generated by our pinned engine, but still bound XML parsing/copy cost.
        if (len(archive.infolist()) > 32 or sum(i.file_size for i in archive.infolist()) > 100_000_000
                or len(set(archive.namelist())) != len(archive.namelist())):
            return None
        for name in ('book.xml', 'sheet#1/sheet#1.xml'):
            if archive.getinfo(name).file_size > 20_000_000:
                return None
        book = ET.fromstring(archive.read('book.xml'))
        sheets = book.findall('sheet')
        if book.get('software-version') != '5.11.0' or len(sheets) != 1 or sheets[0].get('number') != '1':
            return None
        steps = sheets[0].find('steps')
        if steps is None or not {'RHYTHMS', 'PAGE'}.issubset((steps.text or '').split()):
            return None
        sheet = ET.fromstring(archive.read('sheet#1/sheet#1.xml'))
        pages = sheet.findall('page')
        if len(pages) != 1:
            return None
        systems = pages[0].findall('system')
        if not systems or any(len(system.findall('part')) != 1 for system in systems):
            return None
        for system in systems:
            staves = system.findall('part/staff')
            if len(staves) != 2 or any(len(staff.findall('lines/line')) != 5 for staff in staves):
                return None
        pairs, numbers = list(sheet.iter('time-pair')), list(sheet.iter('time-number'))
        if len(pairs) != 2 or len(numbers) != 4 or list(sheet.iter('time-whole')):
            return None
        # Validate the whole graph before invoking any classifier; never change
        # a discarded candidate merely because it has the same staff number.
        selected = []
        for staff in systems[0].findall('part/staff'):
            staff_id = staff.get('id')
            matching_pairs = [p for p in pairs if p.get('id') == staff.findtext('header/time')]
            top = [n for n in numbers if n.get('staff') == staff_id and n.get('side') == 'TOP']
            bottom = [n for n in numbers if n.get('staff') == staff_id and n.get('side') == 'BOTTOM']
            if len(matching_pairs) != 1 or len(top) != 1 or len(bottom) != 1:
                return None
            pair, numerator, denominator = matching_pairs[0], top[0], bottom[0]
            if (pair.get('staff') != staff_id or pair.get('time-rational') != '6/8'
                    or numerator.get('value') != '6' or numerator.get('shape') != 'TIME_SIX'
                    or denominator.get('value') != '8' or denominator.get('shape') != 'TIME_EIGHT'
                    or any(n.get('frozen') != 'true' for n in (pair, numerator, denominator))):
                return None
            glyphs = [g for g in sheet.iter('glyph') if g.get('id') == numerator.get('glyph')]
            if len(glyphs) != 1 or glyphs[0].find('run-table') is None:
                return None
            selected.append((staff_id, pair, numerator, glyphs[0].find('run-table')))
        evidence = []
        for staff_id, pair, numerator, table in selected:
            score = classify(table)
            if not (score['nine'] >= .65 and score['margin'] >= .08):
                return None
            evidence.append(dict(staff=staff_id, **score))
        for _, pair, numerator, _ in selected:
            pair.set('time-rational', '9/8')
            numerator.set('value', '9')
            numerator.set('shape', 'TIME_NINE')
        steps.text = ' '.join(step for step in steps.text.split() if step not in ('RHYTHMS', 'PAGE'))
        with zipfile.ZipFile(target, 'x', zipfile.ZIP_DEFLATED) as output:
            for name in archive.namelist():
                if name == 'book.xml':
                    data = ET.tostring(book, encoding='utf-8', xml_declaration=True)
                elif name == 'sheet#1/sheet#1.xml':
                    data = ET.tostring(sheet, encoding='utf-8', xml_declaration=True)
                else:
                    data = archive.read(name)
                output.writestr(name, data)
        return evidence
