import { act, fireEvent, render, screen } from '@testing-library/react'
import HandsKeyboard from '../HandsKeyboard'

const playNoteNow = jest.fn().mockResolvedValue(true)
jest.mock('@/hooks/useFallingNotesAudio', () => ({ useFallingNotesAudio: () => ({ playNoteNow }) }))
beforeEach(() => playNoteNow.mockReset().mockResolvedValue(true))
afterEach(() => jest.restoreAllMocks())
it('renders five numbered right-hand keys and changes to the mirrored left position', async () => {
  render(<HandsKeyboard />)
  expect(playNoteNow).not.toHaveBeenCalled()
  expect(screen.getAllByRole('button', { name: /손가락 [1-5]/ })).toHaveLength(5)
  const thumb = screen.getByRole('button', { name: '오른손 가운데 도 (4옥타브), 손가락 1 엄지' })
  expect(thumb).toHaveTextContent('도 1')
  await act(async () => { fireEvent.click(thumb) })
  expect(screen.getByRole('status', { name: '누른 건반' })).toHaveTextContent('가운데 도 · 4옥타브 · 오른손 1번 엄지')
  expect(playNoteNow).toHaveBeenCalledWith(60)
  fireEvent.click(screen.getByRole('button', { name: '왼손' }))
  expect(screen.getByRole('button', { name: '왼손' })).toHaveAttribute('aria-pressed', 'true')
  expect(screen.getAllByRole('button', { name: /손가락 [1-5]/ })).toHaveLength(5)
  expect(screen.getByRole('button', { name: '왼손 도 (3옥타브), 손가락 5 새끼손가락' })).toHaveTextContent('도 5')
  expect(screen.getByRole('button', { name: '왼손 솔 (3옥타브), 손가락 1 엄지' })).toHaveTextContent('솔 1')
})
it.each(['throw', 'reject', 'silent'])('keeps finger text working with %s audio', async failure => {
  jest.spyOn(console, 'warn').mockImplementation(() => {})
  if (failure === 'throw') playNoteNow.mockImplementation(() => { throw new Error('audio') })
  else if (failure === 'reject') playNoteNow.mockRejectedValue(new Error('audio'))
  else playNoteNow.mockResolvedValue(false)
  render(<HandsKeyboard />)
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: '오른손 레 (4옥타브), 손가락 2 검지' })) })
  expect(screen.getByRole('status', { name: '누른 건반' })).toHaveTextContent('레 · 4옥타브 · 오른손 2번 검지')
  expect(screen.getByText(/소리를 재생하지 못했어요/)).toBeInTheDocument()
})
it('scrolls only the overflowing region to fit the whole five-key position', () => {
  jest.spyOn(Element.prototype, 'clientWidth', 'get').mockReturnValue(286)
  jest.spyOn(Element.prototype, 'scrollWidth', 'get').mockReturnValue(660)
  render(<HandsKeyboard />)
  const region = screen.getByRole('region', { name: '다섯 손가락 자리 건반 (좌우 스크롤)' })
  expect(region.scrollLeft).toBe(275)
  fireEvent.click(screen.getByRole('button', { name: '왼손' }))
  expect(region.scrollLeft).toBe(0)
  expect(document.activeElement).toBe(document.body)
  expect(window.scrollY).toBe(0)
})

it('announces an audio failure directly below the keyboard and clears it after a successful retry', async () => {
  playNoteNow.mockResolvedValueOnce(false).mockResolvedValueOnce(true)
  render(<HandsKeyboard />)
  const key = screen.getByRole('button', { name: '오른손 가운데 도 (4옥타브), 손가락 1 엄지' })
  await act(async () => { fireEvent.click(key) })
  const status = screen.getByRole('status', { name: '소리 재생 상태' })
  expect(status).toHaveAttribute('aria-live', 'polite')
  expect(status).toHaveTextContent('소리를 재생하지 못했어요.')
  const keyboard = screen.getByRole('region', { name: '다섯 손가락 자리 건반 (좌우 스크롤)' })
  expect(keyboard.nextElementSibling).toBe(status)
  await act(async () => { fireEvent.click(key) })
  expect(status).toBeEmptyDOMElement()
  expect(screen.queryByText(/소리를 재생하지 못했어요/)).toBeNull()
})
it('describes an unnumbered key without inventing a finger assignment', async () => {
  render(<HandsKeyboard />)
  const key = screen.getByRole('button', { name: '도 (5옥타브)' })
  await act(async () => { fireEvent.click(key) })
  expect(key).toHaveAttribute('aria-pressed', 'true')
  expect(screen.getByRole('status', { name: '누른 건반' })).toHaveTextContent('도 · 5옥타브 · 현재 다섯 손가락 자리 밖의 음이에요.')
  expect(playNoteNow).toHaveBeenCalledWith(72)
})
it('clears key selection and guidance when switching hands in either direction', async () => {
  render(<HandsKeyboard />)
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: '오른손 가운데 도 (4옥타브), 손가락 1 엄지' })) })
  fireEvent.click(screen.getByRole('button', { name: '왼손' }))
  const keyboard = screen.getByRole('region', { name: '다섯 손가락 자리 건반 (좌우 스크롤)' })
  const guidance = screen.getByRole('status', { name: '누른 건반' })
  expect(keyboard.querySelectorAll('button[aria-pressed="true"]')).toHaveLength(0)
  expect(guidance).toHaveTextContent('건반을 누르면 계이름과 손가락 번호가 나와요.')
  expect(guidance).not.toHaveTextContent('오른손 1번 엄지')
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: '왼손 도 (3옥타브), 손가락 5 새끼손가락' })) })
  fireEvent.click(screen.getByRole('button', { name: '오른손' }))
  expect(keyboard.querySelectorAll('button[aria-pressed="true"]')).toHaveLength(0)
  expect(guidance).toHaveTextContent('건반을 누르면 계이름과 손가락 번호가 나와요.')
  expect(guidance).not.toHaveTextContent('왼손 5번 새끼손가락')
})
