import { act, fireEvent, render, screen } from '@testing-library/react'
import HandsKeyboard from '../HandsKeyboard'

const playNoteNow = jest.fn().mockResolvedValue(true)
jest.mock('@/hooks/useFallingNotesAudio', () => ({ useFallingNotesAudio: () => ({ playNoteNow }) }))
beforeEach(() => playNoteNow.mockReset().mockResolvedValue(true))
afterEach(() => jest.restoreAllMocks())
it('renders five numbered right-hand keys and changes to the mirrored left position', async () => {
  render(<HandsKeyboard />)
  expect(playNoteNow).not.toHaveBeenCalled()
  expect(screen.getAllByRole('button', { name: /손가락 [1-5]/ })).toHaveLength(5)
  const thumb = screen.getByRole('button', { name: '오른손 가운데 도 (4옥타브), 손가락 1 엄지' })
  expect(thumb).toHaveTextContent('도 1')
  await act(async () => { fireEvent.click(thumb) })
  expect(screen.getByRole('status', { name: '누른 건반' })).toHaveTextContent('가운데 도 · 4옥타브 · 오른손 1번 엄지')
  expect(playNoteNow).toHaveBeenCalledWith(60)
  fireEvent.click(screen.getByRole('button', { name: '왼손' }))
  expect(screen.getByRole('button', { name: '왼손' })).toHaveAttribute('aria-pressed', 'true')
  expect(screen.getAllByRole('button', { name: /손가락 [1-5]/ })).toHaveLength(5)
  expect(screen.getByRole('button', { name: '왼손 도 (3옥타브), 손가락 5 새끼손가락' })).toHaveTextContent('도 5')
  expect(screen.getByRole('button', { name: '왼손 솔 (3옥타브), 손가락 1 엄지' })).toHaveTextContent('솔 1')
})
it.each(['throw', 'reject', 'silent'])('keeps finger text working with %s audio', async failure => {
  jest.spyOn(console, 'warn').mockImplementation(() => {})
  if (failure === 'throw') playNoteNow.mockImplementation(() => { throw new Error('audio') })
  else if (failure === 'reject') playNoteNow.mockRejectedValue(new Error('audio'))
  else playNoteNow.mockResolvedValue(false)
  render(<HandsKeyboard />)
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: '오른손 레 (4옥타브), 손가락 2 검지' })) })
  expect(screen.getByRole('status', { name: '누른 건반' })).toHaveTextContent('레 · 4옥타브 · 오른손 2번 검지')
  expect(screen.getByText(/소리를 재생하지 못했어요/)).toBeInTheDocument()
})
it('scrolls only the overflowing region to fit the whole five-key position', () => {
  jest.spyOn(Element.prototype, 'clientWidth', 'get').mockReturnValue(286)
  jest.spyOn(Element.prototype, 'scrollWidth', 'get').mockReturnValue(660)
  render(<HandsKeyboard />)
  const region = screen.getByRole('region', { name: '다섯 손가락 자리 건반 (좌우 스크롤)' })
  expect(region.scrollLeft).toBe(275)
  fireEvent.click(screen.getByRole('button', { name: '왼손' }))
  expect(region.scrollLeft).toBe(0)
  expect(document.activeElement).toBe(document.body)
  expect(window.scrollY).toBe(0)
})
